experimental_monorepo_root = true

[monorepo]
config_roots = ["content"]

[tools]
pnpm = "latest"
typst = "latest"
typstyle = "latest"
node = "latest"
tombi = "latest"
cue = "latest"

[settings]
lockfile = true

[tasks.build]
run = "pnpm build"

[tasks.format]
run = "pnpm format"