experimental_monorepo_root = true

[monorepo]
config_roots = ["content"]

[tools]
pnpm = "latest"
typst = "latest"
typstyle = "latest"
node = "latest"
tombi = "latest"
cue = "latest"

[settings]
lockfile = true

[env]
_.file = { path = ".env", redact = true }

[tasks.build]
depends = ["//content:build"]
run = "pnpm build"

[tasks.format]
run = "pnpm format"