[tasks.lint]
run = "cue vet -c"

[tasks.format]
run = """
cue fmt
typstyle --inplace norwegian.typ english.typ template.typ
"""

[tasks.build]
run = """
#!/usr/bin/env bash
set -eo pipefail
tags=()
if [ -n "${MY_EMAIL:-}" ]; then tags+=(-t "email=$MY_EMAIL"); fi
if [ -n "${MY_PHONE:-}" ]; then tags+=(-t "phone=$MY_PHONE"); fi
cue export . "${tags[@]}" -e norwegian -f -o norwegian.json
cue export . "${tags[@]}" -e english -f -o english.json
typst compile norwegian.typ ../public/norwegian.pdf
typst compile english.typ ../public/english.pdf
"""